apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-app
  namespace: demo

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
      - name: flask-app
        image: thesanketpawar/flask-app:latest
        ports:
        - containerPort: 5000
